In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[['Banten' 24.0 5000000.0]
 ['DKI Jakarta' nan 3400000.0]
 ['Jawa Barat' 60.0 7350000.0]
 ['Banten' 34.0 3500000.0]
 ['Jawa Barat' 58.0 nan]
 ['DKI Jakarta' nan 8000000.0]
 ['Banten' 21.0 5500000.0]
 ['Banten' 44.0 10000000.0]
 ['Jawa Barat' 40.0 9000000.0]
 ['DKI Jakarta' 51.0 10500000.0]
 ['Banten' 32.0 nan]
 ['Banten' 30.0 6400000.0]
 ['Jawa Barat' 30.0 nan]
 ['DKI Jakarta' 19.0 2200000.0]
 ['DKI Jakarta' 25.0 4500000.0]]


In [6]:
print(y)

['Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No'
 'Yes' 'Yes']


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [9]:
print(x)

[['Banten' 24.0 5000000.0]
 ['DKI Jakarta' 36.0 3400000.0]
 ['Jawa Barat' 60.0 7350000.0]
 ['Banten' 34.0 3500000.0]
 ['Jawa Barat' 58.0 6279166.666666667]
 ['DKI Jakarta' 36.0 8000000.0]
 ['Banten' 21.0 5500000.0]
 ['Banten' 44.0 10000000.0]
 ['Jawa Barat' 40.0 9000000.0]
 ['DKI Jakarta' 51.0 10500000.0]
 ['Banten' 32.0 6279166.666666667]
 ['Banten' 30.0 6400000.0]
 ['Jawa Barat' 30.0 6279166.666666667]
 ['DKI Jakarta' 19.0 2200000.0]
 ['DKI Jakarta' 25.0 4500000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 24.0 5000000.0]
 [0.0 1.0 0.0 36.0 3400000.0]
 [0.0 0.0 1.0 60.0 7350000.0]
 [1.0 0.0 0.0 34.0 3500000.0]
 [0.0 0.0 1.0 58.0 6279166.666666667]
 [0.0 1.0 0.0 36.0 8000000.0]
 [1.0 0.0 0.0 21.0 5500000.0]
 [1.0 0.0 0.0 44.0 10000000.0]
 [0.0 0.0 1.0 40.0 9000000.0]
 [0.0 1.0 0.0 51.0 10500000.0]
 [1.0 0.0 0.0 32.0 6279166.666666667]
 [1.0 0.0 0.0 30.0 6400000.0]
 [0.0 0.0 1.0 30.0 6279166.666666667]
 [0.0 1.0 0.0 19.0 2200000.0]
 [0.0 1.0 0.0 25.0 4500000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[1 0 0 0 1 0 0 1 1 1 0 0 0 1 1]


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [16]:
print(x_train)

[[0.0 0.0 1.0 60.0 7350000.0]
 [1.0 0.0 0.0 32.0 6279166.666666667]
 [0.0 0.0 1.0 58.0 6279166.666666667]
 [0.0 1.0 0.0 36.0 3400000.0]
 [0.0 1.0 0.0 19.0 2200000.0]
 [1.0 0.0 0.0 24.0 5000000.0]
 [0.0 1.0 0.0 25.0 4500000.0]
 [0.0 1.0 0.0 51.0 10500000.0]
 [0.0 0.0 1.0 40.0 9000000.0]
 [0.0 0.0 1.0 30.0 6279166.666666667]
 [1.0 0.0 0.0 30.0 6400000.0]
 [0.0 1.0 0.0 36.0 8000000.0]]


In [17]:
print(x_test)

[[1.0 0.0 0.0 34.0 3500000.0]
 [1.0 0.0 0.0 44.0 10000000.0]
 [1.0 0.0 0.0 21.0 5500000.0]]


In [18]:
print(y_train)

[0 0 1 0 1 1 1 1 1 0 0 0]


In [19]:
print(y_test)

[0 1 0]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [21]:
print(x_train)

[[0.0 0.0 1.0 1.830344610844644 0.48875140873761674]
 [1.0 0.0 0.0 -0.37394137210804557 0.006103523836300829]
 [0.0 0.0 1.0 1.672895612062309 0.006103523836300829]
 [0.0 1.0 0.0 -0.05904337454337561 -1.2915995441279382]
 [0.0 1.0 0.0 -1.3973598641932228 -1.8324656563908917]
 [1.0 0.0 0.0 -1.0037373672373855 -0.5704447277773337]
 [0.0 1.0 0.0 -0.925012867846218 -0.7958056078868976]
 [0.0 1.0 0.0 1.1218241163241367 1.9085249534278694]
 [0.0 0.0 1.0 0.2558546230212943 1.2324423130991777]
 [0.0 0.0 1.0 -0.5313903708903805 0.006103523836300829]
 [1.0 0.0 0.0 -0.5313903708903805 0.0605657365294453]
 [0.0 1.0 0.0 -0.05904337454337561 0.7817205528800498]]


In [22]:
print(x_test)

[[1.0 0.0 0.0 -0.21649237332571059 -1.2465273681060254]
 [1.0 0.0 0.0 0.5707526205859643 1.6831640733183055]
 [1.0 0.0 0.0 -1.239910865410888 -0.3450838476677697]]
